export const jpClassNames: { [key: string]: string } = {
  saber: 'セイバー',
  archer: 'アーチャー',
  lancer: 'ランサー',
  rider: 'ライダー',
  caster: 'キャスター',
  assassin: 'アサシン',
  berserker: 'バーサーカー',
  shielder: 'シールダー',
  ruler: 'ルーラー',
  avenger: 'アヴェンジャー',
  alterEgo: 'アルターエゴ',
  moonCancer: 'ムーンキャンサー',
  foreigner: 'フォーリナー',
  pretender: 'プリテンダー',
}

export const shortClassNames: { [key: string]: string } = {
  saber: '剣',
  archer: '弓',
  lancer: '槍',
  rider: '騎',
  caster: '術',
  assassin: '殺',
  berserker: '狂',
  ruler: '裁',
  avenger: '讐',
  alterEgo: '分',
  moonCancer: '月',
  foreigner: '降',
  pretender: '詐',
  shielder: '盾',
}
